// Creacion de usuario con admin

ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER USERS_API
IDENTIFIED BY "MANG.OSTAS"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON USERS;


 -- PERMISOS PARA EL USUARIO USERS_API
GRANT CREATE SESSION, CREATE TABLE, CREATE USER  TO USERS_API;
GRANT CREATE SEQUENCE TO USERS_API;
GRANT CREATE ROLE TO USERS_API;

GRANT CREATE SESSION TO USERS_API WITH ADMIN OPTION;
GRANT CREATE USER TO USERS_API WITH ADMIN OPTION;
GRANT CREATE VIEW TO USERS_API WITH ADMIN OPTION;
GRANT CREATE ROLE TO USERS_API WITH ADMIN OPTION;


// Ingresamos con el usuario USERS_API y creamos y poblamos la tabla.

CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username VARCHAR2(15),
    password VARCHAR2(10)
);

INSERT INTO Users (username, password) VALUES ('johndoe', 'pass1234');
INSERT INTO Users (username, password) VALUES ('janedoe', 'password');
INSERT INTO Users (username, password) VALUES ('alice123', 'alicepass');
INSERT INTO Users (username, password) VALUES ('bob2020', 'bobpass20');
INSERT INTO Users (username, password) VALUES ('charlie12', 'charpass');


CREATE TABLE recetas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    anio_creacion NUMBER(4) CHECK (anio_creacion BETWEEN 1900 AND 2100),
    vigente CHAR(1) CHECK (vigente IN ('Y', 'N'))
);


INSERT INTO recetas (nombre, anio_creacion, vigente) VALUES ('Paella', 2020, 'Y');
INSERT INTO recetas (nombre, anio_creacion, vigente) VALUES ('Tacos al Pastor', 2019, 'Y');
INSERT INTO recetas (nombre, anio_creacion, vigente) VALUES ('Lasagna', 2018, 'Y');
INSERT INTO recetas (nombre, anio_creacion, vigente) VALUES ('Sushi', 2021, 'Y');
INSERT INTO recetas (nombre, anio_creacion, vigente) VALUES ('Ensalada César', 2022, 'Y');


CREATE TABLE detalle_receta (
    id_receta NUMBER,
    ingredientes VARCHAR2(255) NOT NULL,
    preparacion VARCHAR2(255) NOT NULL,
    FOREIGN KEY (id_receta) REFERENCES recetas(id)
);


INSERT INTO detalle_receta (id_receta, ingredientes, preparacion) VALUES (1, 'Arroz, mariscos, azafrán, pimientos', 'Cocina el arroz con mariscos y añade azafrán para el color.');
INSERT INTO detalle_receta (id_receta, ingredientes, preparacion) VALUES (2, 'Tortillas, carne, cebolla, cilantro', 'Calienta las tortillas y añade carne con cebolla y cilantro.');
INSERT INTO detalle_receta (id_receta, ingredientes, preparacion) VALUES (3, 'Pastas, carne molida, salsa de tomate, queso', 'Cocina la pasta y mezcla con carne y salsa.');
INSERT INTO detalle_receta (id_receta, ingredientes, preparacion) VALUES (4, 'Arroz, pescado, alga nori, vinagre', 'Prepara el arroz, forma sushi y añade pescado y alga.');
INSERT INTO detalle_receta (id_receta, ingredientes, preparacion) VALUES (5, 'Lechuga, pollo, crutones, aderezo', 'Mezcla la lechuga con pollo y añade crutones y aderezo.');


